### ISSUE TITLE
Segmentation problem: not all seeds in group identified

### ISSUE THREAD

**Issue by TaranMeyer** [ai-cfia/nachet-model#13]
**Description**
Model fails to segment out all seeds in an image.

**Expected behavior**
Image has six seeds; model should identify six seeds as well as provide six classifications

**Actual Behavior**
Only five of the seeds were given bounding boxes; two classifications appear to be attached to one bounding box. This error did not occur when the same seeds were arranged in rows, but occurred when they were placed irregularly.

**Supporting Images**
To better understand the issue, please add screenshots:
* **Results**: Include a screenshot of the interface showing the classification error or the issue as it appears in your environment.

![Screenshot 2023-11-24 Capture 2](https://github.com/ai-cfia/nachet-model/assets/142623921/ee143ecf-5377-4649-a4ef-e0f8ee7e8dcb)

* **Source Image**: Attach the actual picture or image used when you encountered the issue.

![Solanum rostratum six seeds 2-2023-11-24](https://github.com/ai-cfia/nachet-model/assets/142623921/b50f16c2-3652-409a-bddb-2f51b76cc933)

* **Microscope Settings**:  
![WIN_20231124_16_39_06_Pro](https://github.com/ai-cfia/nachet-model/assets/142623921/3360a035-0fc4-4308-8e04-4297ff04b4ed)
![WIN_20231124_16_39_16_Pro](https://github.com/ai-cfia/nachet-model/assets/142623921/7f24689e-b89f-4384-a204-223d815ef503)

**Comment by MaxenceGui** [comment]
Seems to be solve with the latest change to Nachet Backend:

- Swin Transformer:

![Image](https://github.com/ai-cfia/nachet-model/assets/96267006/f844c917-a8cb-4833-97f0-d499454d8906)

- Nachet 6seeds

![Image](https://github.com/ai-cfia/nachet-model/assets/96267006/e569cf2a-3572-4a2c-bf3c-ece6225d98c1)
