### ISSUE TITLE
Failure to recognize: model randomly skips one seed in a group, even though all seeds are well-separated.

### ISSUE THREAD

**Issue by TaranMeyer** [ai-cfia/nachet-model#20]
**Description**
Took a group image of 11 seeds, fairly spaced out and oriented so that bounding boxes would not overlap.

**Expected behavior**
11 bounding boxes and 11 IDs would be returned

**Actual Behavior**
All IDs returned were correct (yay!), but one seed is not highlighted by a bounding box and ID # 6 is missing from the results. Presumably the two are related?

**Supporting Images**
To better understand the issue, please add screenshots:
* **Results**: Include a screenshot of the interface showing the classification error or the issue as it appears in your environment.
* 
![image](https://github.com/ai-cfia/nachet-model/assets/142623921/14bed6b2-1b5f-4da6-b484-09c2852c191c)

* **Source Image**: Attach the actual picture or image used when you encountered the issue.
* 
![WIN_20240306_14_03_31_Pro](https://github.com/ai-cfia/nachet-model/assets/142623921/38b260ac-3926-4b60-b9ca-0ec7548284ef)

* **Microscope Settings**:  the microscope settings when the picture was taken.
![WIN_20240306_14_03_39_Pro](https://github.com/ai-cfia/nachet-model/assets/142623921/66db3ff3-b168-48b1-8923-c9bbe3b4db2d)

**Comment by MaxenceGui** [comment]
Seems to be fixe with the latest change in the backend from
* https://github.com/ai-cfia/nachet-backend/issues/62

![image](https://github.com/ai-cfia/nachet-model/assets/96267006/caeeec89-17c2-4815-b711-93609c0290ca)
