### ISSUE TITLE
Cannot access Dataset via Azure ML Api

### ISSUE THREAD

**Issue by RussellJimmies** [ai-cfia/nachet-model#7]
![image](https://github.com/ai-cfia/nachet-model/assets/88112401/b6629a15-9c7c-4eaa-81e0-0c96e45772b2)

Linked Issue: #4

**Comment by RussellJimmies** [comment]
When I inspect the Jobs object, Inputs is empty: 
![image](https://github.com/ai-cfia/nachet-model/assets/88112401/94405967-8d57-4b10-844f-f38e30f63146)

**Comment by MaxenceGui** [comment]
The feature is not going to be implemented.
