### ISSUE TITLE
False Positive: File cabinet recognized as seed

### ISSUE THREAD

**Issue by RussellJimmies** [ai-cfia/nachet-model#9]
**Description**
Model identified the file cabinet as being a seed.

**Expected behavior**
Model would not identify a seed.

**Actual Behavior**
False positive.

**Supporting Images**
To better understand the issue, please add screenshots:
* **Results**:
![image](https://github.com/ai-cfia/nachet-model/assets/88112401/8fcf29f6-b36f-4b1a-8fec-a497ec29edd6)

* **Source Image**: 
![image](https://github.com/ai-cfia/nachet-model/assets/88112401/19ddf3aa-4963-404b-8270-2e41a40329ba)

**Comment by RussellJimmies** [comment]
![FalsePositive-2023-11-21_res](https://github.com/ai-cfia/nachet-model/assets/88112401/50ea4926-1bc0-4d27-bc4e-126899b0b0d0)
![FalsePositive-2023-11-21](https://github.com/ai-cfia/nachet-model/assets/88112401/ae5393cc-a2a8-4ee8-8321-19b44e746d59)

**Comment by TaranMeyer** [comment]
![FP test 1 2023-11-20 capture 15](https://github.com/ai-cfia/nachet-model/assets/142623921/dce2776c-acbb-432d-bfa8-19ebc51ed21d)

False Positive: These seeds are from the same genus as identified, Bromus, but different species than the model was trained on; we would hope they would be identified with a low confidence level, I think.

**Comment by TaranMeyer** [comment]
![TN Test 3 2023-11-20 capture 14](https://github.com/ai-cfia/nachet-model/assets/142623921/1be267ae-a753-4721-84f7-64870bbb0826)

These are soil peds (little clumps of dirt) that are found in grain samples fairly frequently. The model is currently interpreting them as seeds.

**Comment by MaxenceGui** [comment]
## Update

### Description

Test this issue again with Swin Transformer.

### Expected Behaviour

The model will identify no seeds in the image.

### Actual Behaviour

False Positive

### Supporting image

Source image:


![Image](https://github.com/ai-cfia/nachet-model/assets/96267006/307317b0-2ab8-456e-b735-ea5e37bbcb63)

**Comment by RussellJimmies** [comment]
We should probably close this issue, as Amir explained, the model will return a result no matter what. Technically, this isn't a misclassification, it's an improper use of the model.

**Comment by MaxenceGui** [comment]
Closing this issue as the models will try to return a result even if there is no seed in the image. The models' knowledge base context is built around the 15 regulated seed species and doesn't have a broader understanding of the world around it.
